### ISSUE TITLE
Remove need to highlight function name

### ISSUE THREAD

**Issue by lumpysimon** [tripflex/sublime-wp-developer-resources#6]
Is it possible to change the behaviour very slightly, so that you can just right click on a function name, rather than having to double-click to highlight the function name first then right-click? (i.e. the same behaviour as 'Jump to symbol definition' in SublimeCodeIntel)

I know this sounds like a minor thing, but it would save a lot of clicks!

**Comment by tripflex** [comment]
You should be able to just place the cursor inside that function and then right click, i'll have to test it out but technically it should allow you to look up the function without selecting the entire function name
